[project]
name = "tts"
version = "0.1.0"
description = "Learning project with an attempt to create a test case management tool."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastapi[standard]>=0.115.6", "sqlmodel>=0.0.22"]
license = { file = "LICENCE" }
